{
 "title": "Monitoring RateLimiter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(application)" } },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Max RateLimiter Acquire Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance, exception) (rate_limiter_duration_seconds_max)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$app_name\", uri!=\"/actuator/prometheus\"}[$__rate_interval])) by (uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Average RateLimiter Acquire Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance, exception) (rate(rate_limiter_duration_seconds_sum[$__rate_interval])) \n/\n(sum by(instance, exception) (rate(rate_limiter_duration_seconds_count[$__rate_interval]) != 0)) ",
     "legendFormat": "{{instance}}-{{exception}}"
    }
   ]
  },
  {
   "title": "Average Request Duration Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_sum{application=\"$app_name\", uri!=\"/actuator/prometheus\"}[$__rate_interval])) / (sum by(uri) (rate(http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"}[$__rate_interval]) != 0)) ",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"2.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{application=\"$app_name\", uri!=\"/actuator/prometheus\"}) / sum by(uri)(http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Get Success By User",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(item_event_total{event=\"get\"}) by(user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Total Create Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(item_event_total{event=\"create\"}) by(user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Ratelimiter Success by User",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_limiter_event_total{status=\"success\"}) by(user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Ratelimiter Errors By User",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_limiter_event_total{status=\"failure\"}) by(user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Rate Limiter Error Percentage By User",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(user) (rate_limiter_event_total{status=\"failure\"}) / sum by(user) (rate_limiter_event_total{})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Rate Limiter Success Percentage By User",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(user) (rate_limiter_event_total{status=\"success\"}) / sum by(user) (rate_limiter_event_total{})",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}